# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "scsidisk"
edition.workspace = true
rust-version.workspace = true

[dependencies]
disk_backend.workspace = true
scsi_buffers.workspace = true
scsi_core.workspace = true
scsi_defs.workspace = true
scsidisk_resources.workspace = true
hvdef.workspace = true
pal_async.workspace = true
vm_resource.workspace = true

guestmem.workspace = true
vmcore.workspace = true

guid = { workspace = true, features = ["mesh", "inspect"] }
mesh.workspace = true

anyhow.workspace = true
async-trait.workspace = true
inspect.workspace = true
futures.workspace = true
tracing_helpers.workspace = true
parking_lot.workspace = true
stackfuture.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
zerocopy.workspace = true
getrandom.workspace = true

[dev-dependencies]
chipset_device.workspace = true
disk_nvme.workspace = true
disk_prwrap.workspace = true
disklayer_ram.workspace = true
nvme_driver.workspace = true
pci_core.workspace = true
nvme.workspace = true
test_with_tracing.workspace = true
user_driver.workspace = true

[lints]
workspace = true
